# llm_judger.py
import os
import argparse
import json
import re
import time
import pandas as pd
from openai import OpenAI, OpenAIError
import sys
# 行缓冲 + 立即刷新
try:
    sys.stdout.reconfigure(line_buffering=True)
except Exception:
    pass

print("程序启动成功", flush=True)

YUNWU_BASE_URL = "https://api.wlai.vip/v1"
DEFAULT_API_KEY_ENV = "YUNWU_API_KEY"
DEFAULT_API_KEY = os.environ.get(DEFAULT_API_KEY_ENV) or os.environ.get("OPENAI_API_KEY") or ""

DEFAULT_INPUT_FILE = "examples/output_semantic_headers_FAISS.xlsx"
DEFAULT_OUTPUT_FILE = "output/output_semantic_headers_FAISS_Judged.xlsx"

DEFAULT_MODEL = "qwen3-max"

system_prompt = f"""
You are a judger responsible for evaluating answers generated by large language models (LLMs) to questions in Heating, Ventilation, and Air-Conditioning (HVAC) and related/fundamental courses (e.g., building automation and control, industrial ventilation, heat transfer, fluid mechanics).

Evaluation criteria:
(1) **Result Accuracy**: Whether the {{AI-generated answer}} matches the {{official standard answer}} in its final result.  

The output format should be:
**Result Accuracy**: <Only output Yes or No, nothing else>, <Reason (write down the AI-generated result and offical result)>


Provided content:
"""

def parse_block(block: str) -> dict:
    parsed = {
        "Result Accuracy": "",

    }
    lines = [ln.strip() for ln in block.split("\n") if ln.strip()]

    for line in lines:
        if line.startswith("**Result Accuracy**:"):
            content = line.replace("**Result Accuracy**:", "").strip()
            parts = content.split(",", 1)
            parsed["Result Accuracy"] = parts[0].strip() if parts else ""

    return parsed


def call_judger(client: OpenAI, model: str, system_text: str, user_text: str) -> str:
    """Try Responses API first, then fall back to Chat Completions."""
    try:
        response = client.responses.create(
            model=model,
            input=[
                {"role": "system", "content": system_text},
                {"role": "user", "content": user_text},
            ],
            stream=False,
            temperature=0,
        )
        return (response.output_text or "").strip()
    except Exception as first_error:
        print(f"Responses API failed, falling back to chat.completions: {first_error}", flush=True)
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_text},
                {"role": "user", "content": user_text},
            ],
            stream=False,
            temperature=0,
        )
        return (response.choices[0].message.content or "").strip()

def main():
    parser = argparse.ArgumentParser(description="Judge LLM answers from an Excel file and output structured scores to another Excel.")
    parser.add_argument("--gpu", type=int, default=-1, help="GPU index to use; -1 for CPU/no GPU env var.")
    parser.add_argument("--input_file", type=str, default=DEFAULT_INPUT_FILE, help="Path to input .xlsx (must contain columns: question, Answer, Result).")
    parser.add_argument("--output_file", type=str, default=DEFAULT_OUTPUT_FILE, help="Path to output .xlsx.")
    parser.add_argument("--start_index", type=int, default=0, help="Row index to start/resume from (0-based).")
    parser.add_argument(
        "--api_key",
        type=str,
        default=DEFAULT_API_KEY,
        help=f"API key for the model provider. Defaults to env {DEFAULT_API_KEY_ENV} (or OPENAI_API_KEY).",
    )
    parser.add_argument("--model", type=str, default=DEFAULT_MODEL, help="Model name (default: Qwen_3_max).")

    parser.add_argument("--system_prompt_file", type=str, default=None, help="Optional path to a file containing the system prompt.")
    parser.add_argument("--save_every", type=int, default=100, help="Write interim results to Excel every N rows.")
    args = parser.parse_args()

    # Be tolerant of accidental leading/trailing spaces in CLI paths.
    args.input_file = str(args.input_file).strip()
    args.output_file = str(args.output_file).strip()

    if not args.api_key:
        raise SystemExit(f"未提供 API key：请使用 --api_key 或设置环境变量 {DEFAULT_API_KEY_ENV}（或 OPENAI_API_KEY）。")

    # Respect --gpu via CUDA_VISIBLE_DEVICES (useful if any downstream libs care; safe no-op for API calls)
    if args.gpu is not None and args.gpu >= 0:
        os.environ["CUDA_VISIBLE_DEVICES"] = str(args.gpu)
    else:
        # Unset to avoid accidentally grabbing a GPU in some environments
        os.environ["CUDA_VISIBLE_DEVICES"] = ""

    # Initialize client
    # client = OpenAI(api_key=args.api_key, base_url=args.base_url)
    client = OpenAI(api_key=args.api_key, base_url=YUNWU_BASE_URL)

    # Load data
    if not os.path.exists(args.input_file):
        raise FileNotFoundError(f"Input file not found: {args.input_file}")

    output_dir = os.path.dirname(args.output_file)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    df = pd.read_excel(args.input_file)
    required_cols = ["question", "Answer", "Result"]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in input: {missing}. Found columns: {list(df.columns)}")

    results = []
    total = len(df)
    start = max(0, int(args.start_index))

    # If resuming and output file exists, we can load prior results to avoid duplication (optional)
    # Here we keep it simple—always recompute from start_index.

    for index in range(start, total):
        row = df.iloc[index]
        question = str(row["question"]) if pd.notna(row["question"]) else ""
        Answer = str(row["Answer"]) if pd.notna(row["Answer"]) else ""
        Result = str(row["Result"]) if pd.notna(row["Result"]) else ""

        print(f"\n<<<<<<<<<< Processing item entry: {index} / {total-1} <<<<<<<<<<", flush=True)

        # Skip empty triplets gracefully
        if not (question or Answer or Result):
            print("Empty row; skipping.", flush=True)
            continue

        # --- API call with retries ---
        generated_text = ""
        for attempt in range(3):
            try:
                generated_text = call_judger(
                    client=client,
                    model=args.model,
                    system_text=system_prompt,
                    user_text=f"""
**Provided question**: {question}  
**Official standard answer**: {Answer}
**AI-generated answer**: {Result}""",
                )
                break
            except OpenAIError as e:
                print(f"[Attempt {attempt+1}] Error: {e}", flush=True)
                time.sleep(2 * (attempt + 1))
        else:
            print(">>> Failed after 3 attempts, skipping entry.", flush=True)
            # 仍然写一行空评分，便于对齐
            results.append({
                "question": question,
                "Answer": Answer,
                "Result": Result,
                "Result Accuracy": "",

            })
            continue

        # --- Parse the model output ---
        # 用 “**Result Accuracy**:” 作为每个评价块的起点；若没有，按整体作为一个块处理
        qa_blocks = [generated_text]

        any_added = False
        for block in qa_blocks:
            block = block.strip()
            if not block:
                continue

            parsed = parse_block(block)
            results.append({
                "question": question,
                "Answer": Answer,
                "Result": Result,
                **parsed
            })
            any_added = True

        # 如果解析不到有效块，也写一行空评分，避免丢失题干
        if not any_added:
            results.append({
                "question": question,
                "Answer": Answer,
                "Result": Result,
                "Result Accuracy": "",

            })

        # 周期性写盘，避免长任务中断丢失
        if args.save_every > 0 and (index + 1) % args.save_every == 0:
            out_df = pd.DataFrame(results, columns=[
                "question", "Answer", "Result",
                "Result Accuracy",

            ])
            if output_dir:
                os.makedirs(output_dir, exist_ok=True)
            out_df.to_excel(args.output_file, index=False)
            print(f"[Auto-Save] Saved {len(results)} rows to {args.output_file}", flush=True)

    # 最终写盘
    out_df = pd.DataFrame(results, columns=[
        "question", "Answer", "Result",
        "Result Accuracy",

    ])
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    out_df.to_excel(args.output_file, index=False)
    print(f"Saved to {args.output_file}. Total rows written: {len(results)}", flush=True)

if __name__ == "__main__":
    main()